language: python

python:
    - 2.7
    - 2.6
env:
    - NUMPY_VERSION=1.7.1 ONLY_EGG_INFO=false
    - NUMPY_VERSION=1.6.2 ONLY_EGG_INFO=false
    #- NUMPY_VERSION=1.5.1 ONLY_EGG_INFO=false
    #- NUMPY_VERSION=1.4.1 ONLY_EGG_INFO=false
    
before_install:
   # http://about.travis-ci.org/docs/user/gui-and-headless-browsers/
   #- "export DISPLAY=:99.0"
   #- "sh -e /etc/init.d/xvfb start"
   # We do this to make sure we get the dependencies so pip works below
   - sudo apt-get update -qq 
   - sudo apt-get install -qq python-numpy cython libatlas-dev liblapack-dev gfortran
   - sudo apt-get install -qq python-scipy 
install: 
   - export PYTHONIOENCODING=UTF8 # just in case
   - pip install --upgrade "numpy==$NUMPY_VERSION" -q --use-mirrors
   #- pip install scipy --use-mirrors
   - python setup.py install_radex install # I guess?
script: python setup.py test
